apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: lets-encrypt
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-account-secret
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              key: token
              name: {{ .Values.cloudflare.apiToken.secretName }}
            email: {{ .Values.cloudflare.email }}
