apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.acme.issuer }}
spec:
  acme:
    server: {{ .Values.acme.server }}
    privateKeySecretRef:
      name: acme-account-secret
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: {{ .Values.cloudflare.apiToken.secretName }}
              key: token
            email: {{ .Values.cloudflare.email }}
